// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhfVR2QoHJKtiv4A6m1-zuLm3xMqK1Nsc',
    appId: '1:955153149587:web:9668bc543a6972be54e766',
    messagingSenderId: '955153149587',
    projectId: 'pokedata-3d0b6',
    authDomain: 'pokedata-3d0b6.firebaseapp.com',
    databaseURL: 'https://pokedata-3d0b6-default-rtdb.firebaseio.com',
    storageBucket: 'pokedata-3d0b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqIZhgkATWKUblvDvyd6AqBsfkl0d8Eo',
    appId: '1:955153149587:android:5f33256002130b5454e766',
    messagingSenderId: '955153149587',
    projectId: 'pokedata-3d0b6',
    databaseURL: 'https://pokedata-3d0b6-default-rtdb.firebaseio.com',
    storageBucket: 'pokedata-3d0b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6VVvOUYyv9_jIs2WGLGj7_SkmK_Hqmo',
    appId: '1:955153149587:ios:0433979ebabf13cc54e766',
    messagingSenderId: '955153149587',
    projectId: 'pokedata-3d0b6',
    databaseURL: 'https://pokedata-3d0b6-default-rtdb.firebaseio.com',
    storageBucket: 'pokedata-3d0b6.appspot.com',
    iosClientId: '955153149587-tjj9k0v7hkuaelo7kqdvdo1pf9135hoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokeData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH6VVvOUYyv9_jIs2WGLGj7_SkmK_Hqmo',
    appId: '1:955153149587:ios:0433979ebabf13cc54e766',
    messagingSenderId: '955153149587',
    projectId: 'pokedata-3d0b6',
    databaseURL: 'https://pokedata-3d0b6-default-rtdb.firebaseio.com',
    storageBucket: 'pokedata-3d0b6.appspot.com',
    iosClientId: '955153149587-tjj9k0v7hkuaelo7kqdvdo1pf9135hoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokeData',
  );
}
